# Generated by Django 3.1.7 on 2022-04-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades de los estudiantes'},
        ),
        migrations.AddField(
            model_name='estudiante',
            name='hadilidad',
            field=models.ManyToManyField(to='persona.Habilidades'),
        ),
    ]
