# Generated by Django 3.1.7 on 2022-04-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20220412_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='hadilidad',
            new_name='habilidad',
        ),
    ]
