# Generated by Django 3.1.7 on 2022-04-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
    ]
