# Generated by Django 3.1.7 on 2022-04-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
