# Generated by Django 3.1.7 on 2022-04-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncia', '0002_auto_20220421_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
