# Generated by Django 3.1.7 on 2022-04-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncia', '0005_auto_20220426_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='acusado',
            field=models.CharField(max_length=150),
        ),
    ]
