# Generated by Django 3.1.7 on 2022-04-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultad',
            name='nombreCorto',
            field=models.CharField(max_length=10, unique=True, verbose_name='NombreCorto'),
        ),
    ]
